version: "3.9"
services:
  strapi:
    restart: unless-stopped
    image: docker.pkg.github.com/unixfy/gambitprofit-api-backend/gambitprofit-strapi:latest
    expose:
      - 1337
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=mongo
      - DATABASE_NAME=strapi
      - DATABASE_PASSWORD=strapi
      - DATABASE_PORT=27017
      - DATABASE_USERNAME=strapi
      - NODE_ENV=production
      - VIRTUAL_HOST=api.gambitprofit.com
      - VIRTUAL_PORT=1337
      - LETSENCRYPT_HOST=api.gambitprofit.com

  mongo:
    restart: unless-stopped
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=strapi
      - MONGO_INITDB_ROOT_PASSWORD=strapi
      - MONGO_INITDB_DATABASE=strapi
    volumes:
      - ./db:/data/db

  updater:
    restart: unless-stopped
    image: docker.pkg.github.com/unixfy/gambitprofit-api-backend/gambitprofit-updater:latest
    environment:
      - GAMBIT_USERNAME=
      - GAMBIT_PASSWORD=
      - API_USERNAME=
      - API_PASSWORD=

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup

  proxy:
    image: nginxproxy/nginx-proxy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - ENABLE_IPV6=true

  letsencrypt:
    image: nginxproxy/acme-companion:latest
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/.docker/config.json:/config.json
    environment:
      - DEFAULT_EMAIL=admin@unixfy.net

volumes:
  vhost:
  html: